### ISSUE TITLE
Fix cache issue for workflow

### ISSUE THREAD

**Issue by Wendydarby** [VARoadstter/VARoadstter.github.io#4]
From the logs of the failed workflow run for **Deploy Jekyll site to Pages**, here's what I found:

### Problem Identified:
1. **Dependency Change in Gemfile**:
   - The error message indicates that the workflow is trying to install gems in **deployment mode** after changes were made to the `Gemfile`.
   - Specifically, the following dependency was **added** to the `Gemfile`:
     ```
     * jekyll-include-cache
     ```

2. **Deployment Mode Restriction**:
   - In deployment mode, the `Gemfile.lock` file must match the contents of the `Gemfile`. However, since the `Gemfile` was updated and the `Gemfile.lock` was not regenerated, this mismatch caused the failure.

3. **Cache Restoration Warning**:
   - A warning appeared about a failure to restore the Ruby bundler cache. While this may not directly cause the failure, it indicates potential inefficiencies in the caching system.

### Solution Steps:
To fix this issue, you need to update the `Gemfile.lock` file to reflect the changes in the `Gemfile` and ensure the workflow runs correctly.

---

### Steps to Resolve:
1. **Update the `Gemfile.lock`**:
   - On your local machine, run the following commands:
     ```bash
     bundle install
     ```
   - This will regenerate the `Gemfile.lock` file to include the new dependency (`jekyll-include-cache`).

2. **Commit and Push the Changes**:
   - Add the updated `Gemfile.lock` file to your commit:
     ```bash
     git add Gemfile.lock
     git commit -m "Update Gemfile.lock to match Gemfile changes"
     git push
     ```

3. **Retry the Workflow**:
   - Once the `Gemfile.lock` is updated and pushed, GitHub Actions will automatically trigger the workflow, or you can manually re-run it.

4. **Optional: Fix Cache Restoration**:
   - If the warning about cache restoration continues, consider adjusting your workflow configuration for caching. For example:
     ```yaml
     - name: Cache Ruby Gems
       uses: actions/cache@v3
       with:
         path: vendor/bundle
         key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
         restore-keys: |
           ${{ runner.os }}-gems-
     ```

Let me know if you'd like help implementing these changes directly in your repository!
